### ISSUE TITLE
[Bug]: Cannot update Zenless Zone Zero.

### ISSUE THREAD

**Issue by ldy2333** [CollapseLauncher/Collapse#629]
### Affected Version

1.82.7

### Bug Behavior

Cannot update Zenlees Zone Zero, seems due to unable catch the update url.

### Expected Behavior

Update correctly.

### Steps to reproduce

System.NullReferenceException: Oops, the launcher cannot finalize the installation but don't worry, your game has been totally updated.
	Please report this issue to our GitHub here: https://github.com/CollapseLauncher/Collapse/issues/new or come back to the launcher and make sure to use Repair Game in Game Settings button later.
Throw: System.NullReferenceException: Url returns an empty/null data!
   at Hi3Helper.Sophon.SophonManifest.CreateSophonChunkManifestInfoPair(HttpClient client, String url, String matchingField, CancellationToken token) in C:\projects\collapse\Hi3Helper.Sophon\Structs\SophonChunksBranch.cs:line 60
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.AddSophonDiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList, String matchingField, SophonDownloadSpeedLimiter downloadSpeedLimiter) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 1274
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 1106
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 644
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 2610
 ---> System.NullReferenceException: Url returns an empty/null data!
   at Hi3Helper.Sophon.SophonManifest.CreateSophonChunkManifestInfoPair(HttpClient client, String url, String matchingField, CancellationToken token) in C:\projects\collapse\Hi3Helper.Sophon\Structs\SophonChunksBranch.cs:line 60
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.AddSophonDiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList, String matchingField, SophonDownloadSpeedLimiter downloadSpeedLimiter) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 1274
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 1106
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 644
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 2610
   Exception_EndOfInnerExceptionStack

**Comment by ldy2333** [comment]
> Have you downloaded the preload? If you haven't and need to have the game updated ASAP you can go and disable Sophon in the settings for now while we investigate this

Thanks for your help. I could download the update when sophon was disabled now.

**Comment by bagusnl** [comment]
Fixed in 1.82.9

**Comment by XiaoMingXD** [comment]
I still have the same issue when updating the ZZZ global,
I'm using 1.82.11 pre.
It's been a long time since I update the game last time. maybe that affect something.
I think my current game version is 1.1.0.

System.NullReferenceException: Oops, the launcher cannot finalize the installation but don't worry, your game has been totally updated.
	Please report this issue to our GitHub here: https://github.com/CollapseLauncher/Collapse/issues/new or come back to the launcher and make sure to use Repair Game in Game Settings button later.
Throw: System.NullReferenceException: Url returns an empty/null data!
   at Hi3Helper.Sophon.SophonManifest.CreateSophonChunkManifestInfoPair(HttpClient client, String url, String matchingField, CancellationToken token) in C:\projects\collapse\Hi3Helper.Sophon\Structs\SophonChunksBranch.cs:line 52
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.AddSophonDiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList, String matchingField, SophonDownloadSpeedLimiter downloadSpeedLimiter) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.Sophon.cs:line 762
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.Sophon.cs:line 517
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 565
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 2633
 ---> System.NullReferenceException: Url returns an empty/null data!
   at Hi3Helper.Sophon.SophonManifest.CreateSophonChunkManifestInfoPair(HttpClient client, String url, String matchingField, CancellationToken token) in C:\projects\collapse\Hi3Helper.Sophon\Structs\SophonChunksBranch.cs:line 52
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.AddSophonDiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList, String matchingField, SophonDownloadSpeedLimiter downloadSpeedLimiter) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.Sophon.cs:line 762
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.Sophon.cs:line 517
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog) in C:\projects\collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 565
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e) in C:\projects\collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 2633
   Exception_EndOfInnerExceptionStack

**Comment by XiaoMingXD** [comment]
And its do helps when I disable Sophon.

**Comment by neon-nyan** [comment]
Hi there,
Seems like the Sophon API isn't available for update in which the previous version is less than 1.3.0 (eg. 1.2.0, 1.1.0 and so-on), means the URL to the manifest file will return a null reference. Unfortunately, the launcher doesn't have such mechanism where it will fallback to reinstall the whole game instead, just like the legacy method. To get back using the legacy method, you should need to disable Sophon in the app settings.

We will re-open this issue until we implement such fallback function for Sophon method, just to make sure this issue is still on our track.

**Comment by bagusnl** [comment]
Fallback implemented in 1.82.12. Closing issue

**Comment by XiaoMingXD** [comment]
Thank you for fix this! But sadly I don’t have the conditions to test it anymore.

**Comment by bagusnl** [comment]
It was tested with @neon-nyan last night and i saw it working. Shall any issue happens with this mechanism, feel free for anyone to reopen this issue or making a new ticket~
